### ISSUE TITLE
There is no value in gnss.Vx, gnss.Vy and gnss.Vz.

### ISSUE THREAD

**Issue by zhs951226** [GNSSpy-Project/gnsspy#5]
As I have said, when I run the code, I encountered the problem, can you explain it? 
Thanks.

### gnss["Relativistic_clock"] = _relativistic_clock(gnss.X, gnss.Y, gnss.Z, gnss.Vx, gnss.Vy, gnss.Vz)
The error is above.

**Comment by geomsi** [comment]
Hi,

Did you call `_relativistic_clock` function separately from `spp` or any other function? If so, that function requires `gnssDataframe` function to be called, so that the satellites in orbit file and satellite that are visible to the station are matched. If you call `gnssDataframe` correctly, dataframe will have `Relativistic_clock` column already computed.
